# httproute.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-httproute-test
  namespace: upclass-dev01
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - flower.haproxy.laniakea.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: upclass-flower
          port: 5000
