ingress:
  ingress:
    enabled: true
    className: "haproxy"
    annotations:
      nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
      nginx.ingress.kubernetes.io/proxy-set-header-Upgrade: "$http_upgrade"
      nginx.ingress.kubernetes.io/proxy-set-header-Connection: "upgrade"
    hosts:
      - host: backend.npr.upclassedu.com
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: upclass-app
                port:
                  number: 5000
      - host: backend.npr.laniakea.local
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: upclass-app
                port:
                  number: 5000
      - host: flower.npr.laniakea.local
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: upclass-flower
                port:
                  number: 5000
      - host: mailerr.npr.laniakea.local
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: upclass-mailerr
                port:
                  number: 9999
app:
  fullnameOverride: "upclass-app"
beat:
  fullnameOverride: "upclass-beat"
worker:
  fullnameOverride: "upclass-worker"
flower:
  fullnameOverride: "upclass-flower"
mailerr-app:
  fullnameOverride: "upclass-mailerr"
mailerr-worker:
  fullnameOverride: "upclass-mailerr-worker"
mailerr-beat:
  fullnameOverride: "upclass-mailerr-beat"
